---

- name: Install packages
  apt:
    pkg: nfs-common
    state: latest
    update_cache: true
  tags: share

- name: Create directory for import remote FS
  file:
    path: /importfs
    state: directory
    owner: root
    group: root
    mode: 0755
  tags: share

- name: Create directory for automount script
  file:
    path: /etc/autorun
    state: directory
    owner: root
    group: root
    mode: 0755
  tags: share

- name: Copy nfs automount share ps script
  template:
    src: mount_nfs_shares.sh.j2
    dest: /etc/autorun/mount_nfs_shares.sh
    owner: root
    mode: 0744
  notify: Add automount task to crontab
  tags: share

#- name: Copy nfs automount share ps script
#  copy:
#    src: mount_138.151.sh
#    dest: /etc/autorun/mount_138.151.sh
#    owner: root
#    group: root
#    mode: 0777
#  notify: Add automount task to crontab
#  tags: share

#- name: Add automount task to crontab
#  cron:
#    name: "mount_nfs_shares"
#    special_time: reboot
#    job: "/etc/autorun/mount_nfs_shares.sh"
#  tags: share
#  tags: cron