---

#This gathering must redefine variables.
#In particular, 'ansible_hostname' after host renaming role which usually running above
- name: Gather facts
  setup:

- name: Add "{{ ansible_hostname }}" computer to "{{ domain_name }}" domain
  win_domain_membership:
    dns_domain_name: "{{ domain_name }}"
    hostname: "{{ ansible_hostname }}"
    domain_admin_user: "{{ admin_name }}"
    domain_admin_password: "{{ admin_pass }}"
    state: domain
  register: domain_state
  tags:
    - imaging
    - provisioning

- name: Reboot computer
  win_reboot:
  when: domain_state.reboot_required
  tags:
    - imaging
    - provisioning
