---

- name: Configure netplan
  template:
    src: 50-cloud-init.yaml.j2
    dest: /etc/netplan/50-cloud-init.yaml
    owner: root
    group: root
    mode: 0644
  notify: Apply netplan
  tags: network