---

# Install and configure NTP

- package:
    name: ntp
    state: latest

- name: Set NTP config - /etc/ntp.conf
  template:
    src: ntp.conf.j2
    dest: /etc/ntp.conf
    owner: root
    mode: 0644

- name: Restart NTP and Enable on Boot
  service: name=ntp state=restarted enabled=yes
  when: >
        ansible_distribution == 'Debian' or
        ansible_distribution == 'Ubuntu'

- name: Restart NTPd and Enable on Boot
  service: name=ntpd state=restarted enabled=yes
  when: >
        ansible_distribution == 'CentOS' or
        ansible_distribution == 'Red Hat Enterprise Linux'
