---

- name: Add an ms apt signing key
  apt_key:
    url: https://packages.microsoft.com/keys/microsoft.asc
    state: present
  tags: keys

- name: Add ms repo
  copy:
    dest: "/etc/apt/sources.list.d/microsoft.list"
    content: "deb [arch=amd64] https://packages.microsoft.com/repos/microsoft-debian-stretch-prod stretch main"
  tags: repo

- name: Install https transport for apt
  apt:
    pkg: apt-transport-https
    state: present
    update_cache: false
  tags: packages

- name: Install powershell
  apt:
    pkg: powershell
    state: present
    update_cache: true
#   notify: change login shell for user
  tags: packages