---

- name: Install packages
  win_chocolatey:
    name: "{{ item }}"
    state: present
  with_items:
    "{{ packages }}"
  register: install_result
  ignore_errors: True
  tags:
    - imaging

- name: Report install result
  debug:
    var: install_result
  tags:
    - imaging
