
- name: Configure netfilter
  iptables_raw:
    name: allow_mssql_inbound_connections
    ipversion: 4
    keep_unmanaged: yes
    rules: '-A INPUT -p tcp --dport 1433 --src 10.60.1.0/24 -j ACCEPT'
  tags: iptables

- name: Configure netfilter
  iptables:
    comment: allow_mssql_inbound_connections
    table: filter
    chain: INPUT
    protocol: tcp
    match: tcp
    destination_port: 1433
    source: 10.60.1.0/24
    jump: ACCEPT
  tags: iptables
